import type { FormDefinition } from "./types"
import { US_STATES } from "./us-states"

export const i9Form: FormDefinition = {
  id: "i9",
  docType: "I9",
  title: "I-9 Employment Eligibility Verification",
  description: "Federal law requires that every employer who recruits, refers for a fee, or hires an individual for employment in the U.S. must complete Form I-9.",
  sections: [
    { id: "personal", title: "Personal Information" },
    { id: "citizenship", title: "Citizenship Status" },
  ],
  fields: [
    {
      name: "lastName",
      label: "Last Name",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "firstName",
      label: "First Name",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "middleInitial",
      label: "Middle Initial",
      type: "text",
      required: false,
      section: "personal",
    },
    {
      name: "otherLastNames",
      label: "Other Last Names Used",
      type: "text",
      required: false,
      section: "personal",
    },
    {
      name: "address",
      label: "Address",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "apartment",
      label: "Apartment Number",
      type: "text",
      required: false,
      section: "personal",
    },
    {
      name: "city",
      label: "City",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "state",
      label: "State",
      type: "select",
      required: true,
      options: US_STATES,
      section: "personal",
    },
    {
      name: "zip",
      label: "ZIP Code",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "dateOfBirth",
      label: "Date of Birth",
      type: "date",
      required: true,
      section: "personal",
    },
    {
      name: "ssn",
      label: "Social Security Number",
      type: "ssn",
      required: true,
      section: "personal",
    },
    {
      name: "email",
      label: "Email Address",
      type: "text",
      required: false,
      section: "personal",
    },
    {
      name: "phone",
      label: "Phone Number",
      type: "phone",
      required: false,
      section: "personal",
    },
    {
      name: "citizenshipStatus",
      label: "Citizenship Status",
      type: "select",
      required: true,
      options: [
        { value: "us_citizen", label: "US Citizen" },
        { value: "noncitizen_national", label: "Noncitizen National" },
        { value: "lawful_permanent_resident", label: "Lawful Permanent Resident" },
        { value: "alien_authorized", label: "Alien Authorized to Work" },
      ],
      section: "citizenship",
    },
    {
      name: "uscisNumber",
      label: "USCIS Number",
      type: "text",
      required: false,
      helpText: "A-Number or USCIS Number",
      section: "citizenship",
    },
    {
      name: "i94Number",
      label: "I-94 Admission Number",
      type: "text",
      required: false,
      section: "citizenship",
    },
    {
      name: "foreignPassportNumber",
      label: "Foreign Passport Number",
      type: "text",
      required: false,
      section: "citizenship",
    },
    {
      name: "countryOfIssuance",
      label: "Country of Issuance",
      type: "text",
      required: false,
      section: "citizenship",
    },
    {
      name: "workAuthExpiration",
      label: "Expiration Date (if applicable)",
      type: "date",
      required: false,
      section: "citizenship",
    },
  ],
  requiresSignature: true,
}
