import type { FormDefinition } from "./types"
import { US_STATES } from "./us-states"

export const w4Form: FormDefinition = {
  id: "w4",
  docType: "W4",
  title: "W-4 Employee's Withholding Certificate",
  description: "Complete this form so your employer can withhold the correct federal income tax from your pay.",
  sections: [
    { id: "personal", title: "Personal Information" },
    { id: "filing", title: "Filing Status" },
    { id: "adjustments", title: "Adjustments" },
  ],
  fields: [
    {
      name: "firstName",
      label: "First Name",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "middleInitial",
      label: "Middle Initial",
      type: "text",
      required: false,
      validation: {
        maxLength: 1,
      },
      section: "personal",
    },
    {
      name: "lastName",
      label: "Last Name",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "ssn",
      label: "Social Security Number",
      type: "ssn",
      required: true,
      placeholder: "XXX-XX-XXXX",
      section: "personal",
    },
    {
      name: "address",
      label: "Address",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "city",
      label: "City",
      type: "text",
      required: true,
      section: "personal",
    },
    {
      name: "state",
      label: "State",
      type: "select",
      required: true,
      options: US_STATES,
      section: "personal",
    },
    {
      name: "zip",
      label: "ZIP Code",
      type: "text",
      required: true,
      validation: {
        pattern: "^\\d{5}$",
        message: "ZIP code must be 5 digits",
      },
      section: "personal",
    },
    {
      name: "filingStatus",
      label: "Filing Status",
      type: "select",
      required: true,
      options: [
        { value: "single", label: "Single" },
        { value: "married_jointly", label: "Married filing jointly" },
        { value: "head_of_household", label: "Head of household" },
      ],
      section: "filing",
    },
    {
      name: "multipleJobs",
      label: "Multiple Jobs",
      type: "checkbox",
      required: false,
      helpText: "Check if you have more than one job",
      section: "filing",
    },
    {
      name: "dependentsAmount",
      label: "Dependents Amount",
      type: "number",
      required: false,
      helpText: "Total amount from Step 3",
      section: "adjustments",
    },
    {
      name: "otherIncome",
      label: "Other Income",
      type: "number",
      required: false,
      helpText: "Step 4(a)",
      section: "adjustments",
    },
    {
      name: "deductions",
      label: "Deductions",
      type: "number",
      required: false,
      helpText: "Step 4(b)",
      section: "adjustments",
    },
    {
      name: "extraWithholding",
      label: "Extra Withholding",
      type: "number",
      required: false,
      helpText: "Step 4(c)",
      section: "adjustments",
    },
  ],
  requiresSignature: true,
}
